apiVersion: v1
kind: Service
metadata:
  name: tws-ecommerce-app-service
  namespace: easyshop  
spec:
  type: LoadBalancer
  selector:
    app: tws-ecommerce-app
  ports:
    - port: 80
      targetPort: 3000

