name: CI - Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Delete existing 'latest' image from ECR
        run: |
          IMAGE_TAG=latest
          REPOSITORY=tws-ecommerce-app
          REGION=eu-north-1
          ACCOUNT_ID=800261073875

          IMAGE_DIGEST=$(aws ecr describe-images \
            --repository-name $REPOSITORY \
            --region $REGION \
            --query "imageDetails[?contains(imageTags, '$IMAGE_TAG')].imageDigest" \
            --output text)

          if [ -n "$IMAGE_DIGEST" ]; then
            echo "Deleting old image with digest: $IMAGE_DIGEST"
            aws ecr batch-delete-image \
              --repository-name $REPOSITORY \
              --region $REGION \
              --image-ids imageDigest=$IMAGE_DIGEST
          else
            echo "No previous image with tag 'latest' found"
          fi

      - name: Build and Push App Image
        env:
          ECR_REGISTRY: 800261073875.dkr.ecr.eu-north-1.amazonaws.com
          ECR_REPOSITORY: tws-ecommerce-app
        run: |
          IMAGE_TAG=latest
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
